"use client"
import localFont from "next/font/local";
import { TonConnectUIProvider } from "@tonconnect/ui-react";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TonConnectUIProvider manifestUrl="https://amber-top-pelican-488.mypinata.cloud/ipfs/Qme9VB2dVT85xHR66rwgadbM86svUe3Ad84J1i4EKuHGjX">
        {children}
        </TonConnectUIProvider>
      </body>
   
    </html>
  );
}
